### ISSUE TITLE
  [cause]: TypeError [ERR_INVALID_URL]: Invalid URL

### ISSUE THREAD

**Issue by jjohare** [itsKaynine/comfy-ui-client#1]
I think I have everything setup right. Certainly the remote server is processing the request and generating something as it takes a few seconds. I am unsure how to diagnose this TBH.

**Comment by emidiao** [comment]
i got the same error 

 [cause]: TypeError [ERR_INVALID_URL]: Invalid URL
      at new NodeError (node:internal/errors:405:5)
      at new URL (node:internal/url:778:13)
      at new Request (node:internal/deps/undici/undici:7132:25)
      at fetch2 (node:internal/deps/undici/undici:10715:25)
      at Object.fetch (node:internal/deps/undici/undici:11574:18)
      at fetch (node:internal/process/pre_execution:271:25)
      at ComfyUIClient.getHistory (file:///Users/emiliano/Documents/dev/comfy-ui-client-main/dist/index.mjs:194:23)
      at WebSocket.onMessage (file:///Users/emiliano/Documents/dev/comfy-ui-client-main/dist/index.mjs:243:47)
      at WebSocket.emit (node:events:526:35)
      at Receiver.receiverOnMessage (/Users/emiliano/Documents/dev/comfy-ui-client-main/node_modules/ws/lib/websocket.js:1184:20) {
    input: '/82f22909-c041-4b17-b886-cd086f15e800',
    code: 'ERR_INVALID_URL'
  }

**Comment by jjohare** [comment]
If you find a solution please do let me know

**Comment by itsKaynine** [comment]
It appears that this issue only affects the main branch, which has not been published to NPM yet. I've fixed the bug in [this commit](https://github.com/itsKaynine/comfy-ui-client/commit/181ddb91736d67905fedf161807bf921934745dc).

Please pull the latest commit from the main branch and let me know if it resolves the issue.

**Comment by jjohare** [comment]
That works great now thanks!
